import { RouteWaypoint, Junction, SimulatedVehicle } from '../types';

export const BENGALURU_COORDINATES = {
  startLat: 12.9352,
  startLng: 77.6245, // Koramangala
  endLat: 12.9592,
  endLng: 77.6534, // Manipal Hospital, Old Airport Rd
};

// Planned ambulance corridor route waypoints across Bengaluru's high-traffic arterial corridor
export const AMBULANCE_ROUTE_WAYPOINTS: RouteWaypoint[] = [
  {
    id: 'wp-0',
    label: 'Koramangala 80ft Rd Origin',
    x: 80,
    y: 480,
    lat: 12.9348,
    lng: 77.6212,
    speedLimit: 50,
  },
  {
    id: 'wp-1',
    label: 'Sony World Junction',
    x: 230,
    y: 440,
    lat: 12.9365,
    lng: 77.6268,
    speedLimit: 40,
  },
  {
    id: 'wp-2',
    label: 'Ejipura Ring Road Curve',
    x: 390,
    y: 380,
    lat: 12.9421,
    lng: 77.6335,
    speedLimit: 60,
  },
  {
    id: 'wp-3',
    label: 'Domlur Flyover Underpass',
    x: 540,
    y: 310,
    lat: 12.9498,
    lng: 77.6412,
    speedLimit: 50,
  },
  {
    id: 'wp-4',
    label: 'Command Hospital Junction',
    x: 690,
    y: 250,
    lat: 12.9542,
    lng: 77.6481,
    speedLimit: 45,
  },
  {
    id: 'wp-5',
    label: 'Murugeshpalya / Wind Tunnel Rd',
    x: 820,
    y: 200,
    lat: 12.9568,
    lng: 77.6522,
    speedLimit: 50,
  },
  {
    id: 'wp-6',
    label: 'Manipal Hospital Emergency Bay',
    x: 930,
    y: 160,
    lat: 12.9592,
    lng: 77.6565,
    speedLimit: 30,
  },
];

// Major Traffic Junctions along the corridor requiring Green Wave preemption
export const INITIAL_JUNCTIONS: Junction[] = [
  {
    id: 'junc-1',
    name: 'Sony World Signal',
    coordinates: { x: 230, y: 440, lat: 12.9365, lng: 77.6268 },
    distanceFromStartMeters: 420,
    currentDistanceMeters: 420,
    status: 'ALERT',
    signal: 'RED',
    greenWaveOverridden: false,
  },
  {
    id: 'junc-2',
    name: 'Ejipura Junction',
    coordinates: { x: 390, y: 380, lat: 12.9421, lng: 77.6335 },
    distanceFromStartMeters: 920,
    currentDistanceMeters: 920,
    status: 'ALERT',
    signal: 'RED',
    greenWaveOverridden: false,
  },
  {
    id: 'junc-3',
    name: 'Domlur Flyover Crossing',
    coordinates: { x: 540, y: 310, lat: 12.9498, lng: 77.6412 },
    distanceFromStartMeters: 1450,
    currentDistanceMeters: 1450,
    status: 'PREPARE',
    signal: 'YELLOW',
    greenWaveOverridden: false,
  },
  {
    id: 'junc-4',
    name: 'Command Hospital Gate',
    coordinates: { x: 690, y: 250, lat: 12.9542, lng: 77.6481 },
    distanceFromStartMeters: 1950,
    currentDistanceMeters: 1950,
    status: 'MONITOR',
    signal: 'RED',
    greenWaveOverridden: false,
  },
  {
    id: 'junc-5',
    name: 'HAL Heritage Road Cross',
    coordinates: { x: 820, y: 200, lat: 12.9568, lng: 77.6522 },
    distanceFromStartMeters: 2450,
    currentDistanceMeters: 2450,
    status: 'MONITOR',
    signal: 'RED',
    greenWaveOverridden: false,
  },
];

// Background streets and cross-lanes for realistic city rendering
export const BENGALURU_SECONDARY_STREETS = [
  // 100ft road Indiranagar crossing Domlur
  { from: { x: 540, y: 50 }, to: { x: 540, y: 560 }, name: '100 Feet Rd (Indiranagar)' },
  // Koramangala 80ft road cross
  { from: { x: 230, y: 220 }, to: { x: 230, y: 580 }, name: 'Sony World 80ft Rd' },
  // Ejipura main link
  { from: { x: 390, y: 150 }, to: { x: 390, y: 560 }, name: 'Ejipura Main Rd' },
  // Wind Tunnel road cross
  { from: { x: 820, y: 80 }, to: { x: 820, y: 480 }, name: 'Wind Tunnel Rd' },
  // Diagonal Old Airport parallel road
  { from: { x: 50, y: 280 }, to: { x: 920, y: 80 }, name: 'HAL Old Airport Service Corridor' },
  // Southern residential arterial
  { from: { x: 60, y: 540 }, to: { x: 850, y: 480 }, name: 'Sarjapur Link Bypass' },
];

// Landmarks
export const BENGALURU_LANDMARKS = [
  { name: 'Koramangala BDA Complex', x: 120, y: 410, type: 'commercial' },
  { name: 'Sony World Cross', x: 250, y: 470, type: 'junction' },
  { name: 'Embassy Golf Links (EGL)', x: 480, y: 420, type: 'techpark' },
  { name: 'Domlur Flyover Circle', x: 550, y: 270, type: 'junction' },
  { name: 'Command Hospital Air Force', x: 690, y: 190, type: 'hospital' },
  { name: 'HAL Aerospace Museum', x: 870, y: 270, type: 'landmark' },
  { name: 'Manipal Hospital (Emergency)', x: 930, y: 110, type: 'hospital_target' },
];

// Simulated vehicles with authentic Bengaluru vehicle profiles
export const INITIAL_SIMULATED_VEHICLES: SimulatedVehicle[] = [
  {
    id: 'v-101',
    plateNumber: 'KA-01-EA-4912',
    type: 'auto_rickshaw',
    position: { x: 140, y: 462, lat: 12.9355, lng: 77.623 },
    heading: 345,
    speed: 32,
    status: 'NORMAL',
    alertLevel: 'NONE',
    distanceToAmbulance: 70,
    isAheadOfAmbulance: true,
    angleRelativeToRoute: 10,
    timeToInterceptSecs: 9,
    clearedToShoulder: false,
    lateralOffset: 0,
    laneIndex: 1,
    driverName: 'Ramesh Gowda',
    vehicleModel: 'Bajaj RE Auto',
  },
  {
    id: 'v-103',
    plateNumber: 'KA-04-MB-221',
    type: 'car',
    position: { x: 280, y: 422, lat: 12.9378, lng: 77.6285 },
    heading: 335,
    speed: 38,
    status: 'NORMAL',
    alertLevel: 'NONE',
    distanceToAmbulance: 220,
    isAheadOfAmbulance: true,
    angleRelativeToRoute: 8,
    timeToInterceptSecs: 18,
    clearedToShoulder: false,
    lateralOffset: 0,
    laneIndex: 2,
    driverName: 'Priya Sharma',
    vehicleModel: 'Hyundai Creta',
  },
  {
    id: 'v-108',
    plateNumber: 'KA-05-BMTC-500D',
    type: 'bus',
    position: { x: 440, y: 355, lat: 12.9445, lng: 77.636 },
    heading: 335,
    speed: 26,
    status: 'NORMAL',
    alertLevel: 'NONE',
    distanceToAmbulance: 420,
    isAheadOfAmbulance: true,
    angleRelativeToRoute: 12,
    timeToInterceptSecs: 32,
    clearedToShoulder: false,
    lateralOffset: 0,
    laneIndex: 1,
    driverName: 'Manjunath B.',
    vehicleModel: 'BMTC Electric AC',
  },
  {
    id: 'v-112',
    plateNumber: 'KA-03-HY-8812',
    type: 'car',
    position: { x: 500, y: 328, lat: 12.9475, lng: 77.639 },
    heading: 330,
    speed: 42,
    status: 'NORMAL',
    alertLevel: 'NONE',
    distanceToAmbulance: 510,
    isAheadOfAmbulance: true,
    angleRelativeToRoute: 5,
    timeToInterceptSecs: 41,
    clearedToShoulder: false,
    lateralOffset: 0,
    laneIndex: 2,
    driverName: 'Anand Kumar',
    vehicleModel: 'Tata Nexon EV',
  },
  {
    id: 'v-115',
    plateNumber: 'KA-51-EQ-9110',
    type: 'bike',
    position: { x: 610, y: 282, lat: 12.9515, lng: 77.6442 },
    heading: 328,
    speed: 40,
    status: 'NORMAL',
    alertLevel: 'NONE',
    distanceToAmbulance: 660,
    isAheadOfAmbulance: true,
    angleRelativeToRoute: 7,
    timeToInterceptSecs: 52,
    clearedToShoulder: false,
    lateralOffset: 0,
    laneIndex: 0,
    driverName: 'Sanjay Verma (Delivery)',
    vehicleModel: 'Hero Splendor',
  },
  {
    id: 'v-120',
    plateNumber: 'KA-01-MJ-6003',
    type: 'car',
    position: { x: 740, y: 232, lat: 12.955, lng: 77.6498 },
    heading: 325,
    speed: 35,
    status: 'NORMAL',
    alertLevel: 'NONE',
    distanceToAmbulance: 830,
    isAheadOfAmbulance: true,
    angleRelativeToRoute: 10,
    timeToInterceptSecs: 68,
    clearedToShoulder: false,
    lateralOffset: 0,
    laneIndex: 2,
    driverName: 'Deepa Rajan',
    vehicleModel: 'Maruti Suzuki Baleno',
  },
  {
    id: 'v-125',
    plateNumber: 'KA-04-F-3388',
    type: 'auto_rickshaw',
    position: { x: 860, y: 185, lat: 12.9575, lng: 77.6538 },
    heading: 325,
    speed: 28,
    status: 'NORMAL',
    alertLevel: 'NONE',
    distanceToAmbulance: 980,
    isAheadOfAmbulance: true,
    angleRelativeToRoute: 4,
    timeToInterceptSecs: 82,
    clearedToShoulder: false,
    lateralOffset: 0,
    laneIndex: 1,
    driverName: 'Karthik S.',
    vehicleModel: 'Piaggio Ape',
  },
  // Irrelevant vehicles (behind the ambulance, or on cross streets moving away - SHOULD RECEIVE NO ALERT)
  {
    id: 'v-901',
    plateNumber: 'KA-01-AA-1100',
    type: 'car',
    position: { x: 50, y: 520, lat: 12.933, lng: 77.619 },
    heading: 160, // moving away / behind
    speed: 30,
    status: 'NORMAL',
    alertLevel: 'NONE',
    distanceToAmbulance: 60,
    isAheadOfAmbulance: false,
    angleRelativeToRoute: 170,
    timeToInterceptSecs: -1,
    clearedToShoulder: false,
    lateralOffset: 0,
    laneIndex: 1,
    driverName: 'Vikas Rao (Trailing)',
    vehicleModel: 'Honda City',
  },
  {
    id: 'v-902',
    plateNumber: 'KA-03-BB-9922',
    type: 'car',
    position: { x: 230, y: 310, lat: 12.941, lng: 77.6268 },
    heading: 0, // north on 80ft cross-street, perpendicular
    speed: 36,
    status: 'NORMAL',
    alertLevel: 'NONE',
    distanceToAmbulance: 160,
    isAheadOfAmbulance: false,
    angleRelativeToRoute: 90,
    timeToInterceptSecs: -1,
    clearedToShoulder: false,
    lateralOffset: 0,
    laneIndex: 0,
    driverName: 'Shalini K. (Cross Street)',
    vehicleModel: 'Kia Seltos',
  },
  {
    id: 'v-903',
    plateNumber: 'KA-02-ZZ-4411',
    type: 'bike',
    position: { x: 540, y: 440, lat: 12.945, lng: 77.6412 },
    heading: 180, // south on 100ft road Indiranagar, moving away
    speed: 45,
    status: 'NORMAL',
    alertLevel: 'NONE',
    distanceToAmbulance: 250,
    isAheadOfAmbulance: false,
    angleRelativeToRoute: 120,
    timeToInterceptSecs: -1,
    clearedToShoulder: false,
    lateralOffset: 0,
    laneIndex: 1,
    driverName: 'Arjun Das (Cross Lane)',
    vehicleModel: 'Royal Enfield',
  },
];
